name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project # ✅ safe checkout path

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: project

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Static Analysis (Checkstyle, SpotBugs, PMD)
        run: mvn clean verify

      - name: Run TestNG Suite
        run: mvn test -DsuiteXmlFile=testng.xml

      - name: Upload TestNG Reports
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: project/test-output/

      - name: Upload Static Analysis Reports
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-reports
          path: project/target/site/
